---
title: Invitation
author: ''
date: '2020-10-29'
slug: []
categories: []
tags: []
---

# INVITATION FOR THE THIRD INTERNATIONAL CONFERENCE ON “SEEKING WAYS TO ELIMINATE TUBERCULOSIS IN ASIA”

It is our pleasure to invite you to submit abstracts for the 3rd International conference on “Seeking ways to eliminate TB in Asia”. The conference will be held online on the 10th of December 2020 due to the novel coronavirus pandemic.
The online conference is being organized by the National Center for Communicable Diseases (NCCD) under the auspices of the Ministry of Health of Mongolia. The purposes of the conference are to exchange information about local TB situation and control practices of the participating countries as well as to learn best practices from each other and to collaborate in research and development in order to find ways to end TB in Asia. 

We are anticipating participation from following countries:
Mongolia, Russia, China, Japan, North Korea, South Korea and Taiwan. 

```{r}

```


Conference sessions (preliminary): 
Session I: Impact of COVID-19 pandemic on TB programs in Asia
Session II: Emerging technologies in the field of TB control, diagnosis and treatment
Session III: Systematic TB screening and DR-TB management 

Deadline for abstract submission: 20 November 2020
All abstracts will be eligible for oral presentation and will be published in the online conference abstracts book. 
We will shortly send a link of the online conference for registration and abstract submission.

Abstract requirements: 
⮚	Written in English
⮚	Maximum of 250 words, excluding title, headings, and authors’ names and affiliations
⮚	The body of the abstract must contain the following sections (Note: section names must be included in the abstract and written in CAPITAL LETTERS):
▪	TITLE
▪	AUTHORS (last names and initials only, omit degrees), institutions, country; underline the name of the presenting author and e-mail address 
▪	BACKGROUND 
▪	DESIGN/METHODS or INTERVENTION/RESPONSE
▪	RESULTS (Give both numbers and proportions, where applicable) 
▪	CONCLUSION

PLEASE RSVP ABOUT YOUR PARTICIPATION IN THE CONFERENCE BY 15 NOVEMBER 2020 

Questions and inquiries: Dr Temuulen Enebish, Department of TB Surveillance and Research, NCCD, Ulaanbaatar, Mongolia. 
E-mail: temuulen@gmail.com	

Sincerely yours, 


Prof. NYAMKHUU DULMAA
Director-General
National Center for Communicable Diseases 
Ministry of Health of Mongolia

